version: '3.8'

services:
  db:
    image: postgres:16
    container_name: gtnh_postgres
    environment:
      POSTGRES_USER: alv
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bookdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
